# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>. For any questions
# about this software or licensing, please email opensource@seagate.com or
# cortx-questions@seagate.com.

cluster:
   cluster_id: CC01
   server_nodes:
     abc25957545942cfa728b74cead1a882: srvnode1
   srvnode1:
      site_id: DC01
      rack_id: RC01
      node_id: SN01
      storage_set_id: ST01
      operating_system: centos7
      storage:
         enclosure_id: enclosure_1
      bmc:
         ip: 127.0.0.1
         secret: admin
         user: admin

storage:
   enclosure_1:
      type:
      controller:
         primary:
            ip: 127.0.0.1
            port: 28200
         secondary:
            ip: 127.0.0.1
            port: 28200
         user: manage
         password: gAAAAABgB8k2R7NuvqUc0wvwac8kfmEQpVNYUEN2iZTTuqX7lzHTKxEyDvd26MKJPgQrB14sDEfW067PAG1w-vki3zmVvn6zKA==
         type:

rsyslog:
   host: localhost
   port: 514

release:
   product: LDR_R2
   setup: cortx
